[package]
name = "matryoshka_demo_native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
matryoshka-demo-core = { path = "../core", features = ["std"] }
magnus = { version = "0.7", features = ["embed"] }
